
services:
  sentiment-sense:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sentiment-sense
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - LOG_LEVEL=INFO
      - MODEL_NAME=cardiffnlp/twitter-roberta-base-sentiment-latest
      - MAX_TEXT_LENGTH=512
      - BATCH_SIZE_LIMIT=10
      - ENABLE_MODEL_CACHE=true
    volumes:
      # Optional: Mount model cache directory to avoid repeated downloads
      - model_cache:/home/appuser/.cache/huggingface
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

volumes:
  model_cache:
    driver: local
