apiVersion: v1
kind: Namespace
metadata:
  name: sentiment-sense
  labels:
    name: sentiment-sense
    app: sentiment-sense
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    app: monitoring
