apiVersion: v1
kind: Secret
metadata:
  name: sentiment-sense-secret
  namespace: sentiment-sense
  labels:
    app: sentiment-sense
type: Opaque
data:
  # Base64 encoded values
  # To encode: echo -n "your-value" | base64
  
  # Alert Email (base64 encoded)
  # Example: echo -n "admin@example.com" | base64
  ALERT_EMAIL: YWRtaW5AZXhhbXBsZS5jb20=
  
  # Slack Webhook (base64 encoded) - Optional
  # Example: echo -n "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK" | base64
  # ALERT_SLACK_WEBHOOK: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvWU9VUi9TTEFDS1dFQkhPT0s=
  
  # Grafana Admin Password (base64 encoded)
  # Example: echo -n "admin123" | base64
  GRAFANA_ADMIN_PASSWORD: YWRtaW4xMjM=

---
# Note: In production, use proper secret management tools like:
# - Google Secret Manager
# - AWS Secrets Manager  
# - Azure Key Vault
# - HashiCorp Vault
# - Kubernetes External Secrets Operator
