apiVersion: v1
kind: Service
metadata:
  name: sentiment-sense-service
  namespace: sentiment-sense
  labels:
    app: sentiment-sense
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP  # Internal access only for quick start
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: sentiment-sense

---
# Optional: LoadBalancer service for external access
# Uncomment if you want external access without ingress
apiVersion: v1
kind: Service
metadata:
  name: sentiment-sense-external
  namespace: sentiment-sense
  labels:
    app: sentiment-sense
    service-type: external
spec:
  type: LoadBalancer  # Creates external load balancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: sentiment-sense
